- name: Disable SELINUX 
  shell: | 
   /usr/sbin/setenforce 0
   sed -i 's/SELINUX=permissive/SELINUX=disabled/' /etc/sysconfig/selinux

- name: Disable firewalld
  shell: | 
   systemctl disable firewalld
   systemctl stop firewalld

- name: Disable swap 
  shell: | 
   /usr/sbin/swapoff -a
   sed -i 's/^.*swap/#&/' /etc/fstab  


- name: Add Netbridge config 
  lineinfile:
    path: /etc/sysctl.d/k8s.conf
    create: yes
    state: present
    line: |
     net.bridge.bridge-nf-call-ip6tables = 1
     net.bridge.bridge-nf-call-iptables = 1
     net.ipv4.ip_forward = 1
     vm.swappiness=0

- name: enable forwarding 
  shell: |
   /usr/sbin/iptables -P FORWARD ACCEPT
   /usr/sbin/sysctl --system
  
