- name: Remove file if exist 
  file:
    path: /root/k8s-hard-way/certs/cluster-role.yaml
    state: absent

- name: Create CLUSTER-ROLE.yaml
  lineinfile:
    path: /root/k8s-hard-way/certs/cluster-role.yaml
    create: yes
    state: present
    line: |  
     apiVersion: rbac.authorization.k8s.io/v1beta1
     kind: ClusterRole
     metadata:
      annotations:
       rbac.authorization.kubernetes.io/autoupdate: "true"
      labels:
       kubernetes.io/bootstrapping: rbac-defaults
      name: system:kube-apiserver-to-kubelet
     rules:
     - apiGroups:
       - ""
       resources:
       - nodes/proxy
       - nodes/stats
       - nodes/log
       - nodes/spec
       - nodes/metrics
       verbs:
       - "*"

- name: Remove file if exist
  file:
    path: /root/k8s-hard-way/certs/cluster-binding.yaml
    state: absent

- name: Create CLUSTER-ROLE-BINDING.yaml
  lineinfile:
    path: /root/k8s-hard-way/certs/cluster-binding.yaml
    create: yes
    state: present
    line: |
     apiVersion: rbac.authorization.k8s.io/v1beta1
     kind: ClusterRoleBinding
     metadata:
      name: system:kube-apiserver
      namespace: ""
     roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: ClusterRole
      name: system:kube-apiserver-to-kubelet
     subjects:
     - apiGroup: rbac.authorization.k8s.io
       kind: User
       name: kube-apiserver


- name: Apply Cluster-role
  shell: |
   /usr/local/bin/kubectl apply --kubeconfig /root/admin.kubeconfig -f /root/k8s-hard-way/certs/cluster-role.yaml 
   /usr/local/bin/kubectl apply --kubeconfig /root/admin.kubeconfig -f /root/k8s-hard-way/certs/cluster-binding.yaml 

