  - name: Installing Docker 
    shell: |
     yum install -y yum-utils device-mapper-persistent-data lvm2
     yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
     yum install docker-ce -y

  - name: Starting and Enabling Docker Service 
    service:
     name: docker
     state: started
     enabled: yes
